enum SocketEventType {
    USER_JOIN_CHAT_EVENT = 'USER_JOIN_CHAT_EVENT',
    USER_LEAVE_CHAT_EVENT = 'USER_LEAVE_CHAT_EVENT',
    NEW_CHAT_MESSAGE_EVENT = 'NEW_CHAT_MESSAGE_EVENT',
    START_TYPING_MESSAGE_EVENT = 'START_TYPING_MESSAGE_EVENT',
    STOP_TYPING_MESSAGE_EVENT = 'STOP_TYPING_MESSAGE_EVENT',
}

export default SocketEventType
